server {
    listen 80;
    listen [::]:80;

    server_name node82.webte.fei.stuba.sk;
    root /var/www/node82.webte.fei.stuba.sk/public;

    index index.php index.html;
    charset utf-8;

    access_log /var/log/nginx/node82.webte.fei.stuba.sk.access.log;
    error_log /var/log/nginx/node82.webte.fei.stuba.sk.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
